#!/usr/bin/env python3
"""Rebuild the self-hosted Tabler Icons subset used by the site.

Scans web/templates, admin/templates and non-test Go files for `ti-*`
icon classes, downloads the pinned @tabler/icons-webfont release from
jsDelivr, keeps only the used glyphs (fontTools subset -> WOFF2) and writes:

  web/static/fonts/tabler-icons.woff2
  web/static/fonts/LICENSE-tabler-icons.txt   (MIT, shipped next to the font)
  web/static/css/icons.css                    (@font-face + used .ti-* rules)

Run from the repo root after adding a new icon to a template
(internal/web/icons_test.go fails until you do):

  pip install --user fonttools brotli
  python3 scripts/tabler-icons-subset.py
"""

import hashlib
import pathlib
import re
import subprocess
import sys
import tempfile
import urllib.request

VERSION = "3.31.0"
CDN = f"https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@{VERSION}"
ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_OUT = ROOT / "web/static/fonts/tabler-icons.woff2"
LICENSE_OUT = ROOT / "web/static/fonts/LICENSE-tabler-icons.txt"
CSS_OUT = ROOT / "web/static/css/icons.css"
# Must match assetHashLen in internal/web/assets.go so the font URL in the
# CSS carries the same ?v= the static handler treats as "current".
ASSET_HASH_LEN = 10

# Same patterns as internal/web/icons_test.go.
TEMPLATE_ICON = re.compile(r"(?:^|[^A-Za-z0-9_-])(ti-[a-z0-9]+(?:-[a-z0-9]+)*)")
GO_ICON = re.compile(r"\bti (ti-[a-z0-9]+(?:-[a-z0-9]+)*)")


def used_icons():
    names = set()
    for d in ("web/templates", "admin/templates"):
        for p in (ROOT / d).rglob("*.gohtml"):
            names.update(TEMPLATE_ICON.findall(p.read_text(encoding="utf-8")))
    for d in ("internal", "cmd"):
        for p in (ROOT / d).rglob("*.go"):
            if p.name.endswith("_test.go"):
                continue
            names.update(GO_ICON.findall(p.read_text(encoding="utf-8")))
    return sorted(names)


def fetch(rel):
    with urllib.request.urlopen(f"{CDN}/{rel}", timeout=60) as r:  # noqa: S310 - fixed https URL
        return r.read()


def main():
    icons = used_icons()
    css = fetch("dist/tabler-icons.min.css").decode("utf-8")
    rules = dict(re.findall(r'\.(ti-[a-z0-9-]+):before\{content:"\\([0-9a-f]+)"\}', css))
    missing = [n for n in icons if n not in rules]
    if missing:
        sys.exit(f"unknown Tabler {VERSION} icons: {', '.join(missing)}")

    with tempfile.TemporaryDirectory() as tmp:
        full = pathlib.Path(tmp) / "tabler-icons.woff2"
        full.write_bytes(fetch("dist/fonts/tabler-icons.woff2"))
        unicodes = ",".join(f"U+{rules[n]}" for n in icons)
        FONT_OUT.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            [sys.executable, "-m", "fontTools.subset", str(full),
             f"--unicodes={unicodes}", "--flavor=woff2", "--no-hinting",
             "--layout-features=", "--name-IDs=*", "--name-languages=*",
             "--notdef-outline", f"--output-file={FONT_OUT}"],
            check=True,
        )
    LICENSE_OUT.write_bytes(fetch("LICENSE"))

    font_hash = hashlib.sha256(FONT_OUT.read_bytes()).hexdigest()[:ASSET_HASH_LEN]
    lines = [
        f"/* Tabler Icons {VERSION} (MIT, see ../fonts/LICENSE-tabler-icons.txt) - subset.",
        "   Generated by scripts/tabler-icons-subset.py; do not edit by hand. */",
        '@font-face{font-family:"tabler-icons";font-style:normal;font-weight:400;'
        f'font-display:swap;src:url("../fonts/tabler-icons.woff2?v={font_hash}") format("woff2")}}',
        '.ti{font-family:"tabler-icons" !important;speak:none;font-style:normal;'
        "font-weight:normal;font-variant:normal;text-transform:none;line-height:1;"
        "-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}",
    ]
    lines += [f'.{n}:before{{content:"\\{rules[n]}"}}' for n in icons]
    CSS_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(icons)} icons, font {FONT_OUT.stat().st_size} bytes, css {CSS_OUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
